carts/urls.py
from django.urls import path
from .import views

urlpatterns = [
    
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('store/',include('store.urls')),
    path('cart/',include('app_booking.urls')),
    path('accounts/',include('accounts.urls')),
] + static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from greatkart import views
from . import views
urlpatterns = [
    path('',views.store,name='store'),
    path('category/<slug:category_slug>/',views.store,name='products_by_category'),
    path('location/<slug:location_slug>/',views.store,name='products_by_location'),
    path('category/<slug:category_slug>/<slug:product_slug>/',views.product_detail,name='product_detail'),
    path('search/',views.search,name='search'),
    path('submit_review/<int:product_id>/',views.submit_review,name='submit_review'),
]

carts/models.py
from email.policy import default
from django.db import models
from store.models import Product

# Create your models here.
class Cart(models.Model):
    id = models.AutoField(primary_key=True)
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    id = models.AutoField(primary_key=True)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart    = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.ImageField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.product

store/models.py
from audioop import avg
import profile
from tabnanny import verbose
from django.urls import reverse
from django.db import models
from category.models import Category
from accounts.models import Account
from django.db.models import Avg,Count
from app_location.models import Location
from accounts.models import UserProfile

# Create your models here.
class Product(models.Model):
    id = models.AutoField(primary_key=True)
    product_name        = models.CharField(max_length=200,unique=True)
    slug                = models.SlugField(max_length=200,unique=True)
    description         = models.TextField(max_length=500,blank=True)
    price               = models.IntegerField()
    images              = models.ImageField(upload_to='photos/products')
    stock               = models.IntegerField()
    is_available        = models.BooleanField(default=True)
    category            = models.ForeignKey(Category,on_delete=models.CASCADE)
    location            = models.ForeignKey(Location,on_delete=models.CASCADE)
    created_date        = models.DateTimeField(auto_now_add=True)
    modified_date       = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name  

    def averagereview(self):
        reviews = ReviewRating.objects.filter(product=self,status=True).aggregate(average=Avg('rating'))
        avg =0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countreview(self):
        reviews = ReviewRating.objects.filter(product=self,status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count


    def get_url(self):
        return reverse('product_detail',args=[self.category.slug,self.slug])

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager,self).filter(variation_category='color',is_active=True)

    def sizes(self):
        return super(VariationManager,self).filter(variation_category='size',is_active=True)


variation_category_choice = (
    ('color','color'),
    ('size','size'),
)

class Variation(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100,choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __unicode__(self):
        return self.product.product_name


class ReviewRating(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(Account,on_delete= models.CASCADE)
    subject = models.CharField(max_length=100,blank=True)
    review = models.TextField(max_length=500,blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20,blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.product_name


class ProductGallery(models.Model):
    product = models.ForeignKey(Product,default=None,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products')


    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

store/forms.py
from socket import fromshare
from django import forms
from .models import ReviewRating

class Reviewform(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = {'subject','review','rating'}

carts/views.py
from http.client import HTTPResponse
from django.shortcuts import render,redirect
from store.models import Product
from .models import Cart, CartItem

# Create your views here.
"""def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request)) #get the cart using the cart_id present in the session

    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
    cart.save()
    cart_item = CartItem.objects.filter(product=product,cart=cart)
    if cart_item.exists:
        cart_item.quantity += 1
        cart_item.save()
    else:
        c_item = CartItem.objects.create(
            product=product,
            cart=cart,
            quantity=1,
        )
        c_item.save()

    
    return redirect('cart')



def cart(request,total=0,quantity=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity )
            quantity += cart_item.quantity
    except ObjectNotExist:
        pass

    contex = {
        'total':total,
        'quantity':quantity,
        'cart_items':cart_items,
    }

    return render(request,'store/cart.html')"""

store/views.py
from http.client import HTTPResponse
from unicodedata import category
from django.shortcuts import render,get_object_or_404,redirect
from django.db.models import Q
from django.contrib import messages

from category.models import Category
from .models import Product, ProductGallery,ReviewRating
from app_location.models import Location
from .forms import Reviewform
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator

# Create your views here.
def store(request,category_slug=None,location_slug=None):
    categories = None
    products = None

    if category_slug !=None:
        categories = get_object_or_404(Category,slug=category_slug)
        products = Product.objects.filter(category=categories,is_available=True)
        paginator = Paginator(products,3)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        products_count = products.count()

    elif location_slug != None:
        location = get_object_or_404(Location,slug=location_slug)
        products = Product.objects.filter(location=location,is_available=True)
        paginator = Paginator(products,3)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        products_count = products.count()


    else:
        products = Product.objects.all().filter(is_available=True).order_by('-id')
        paginator = Paginator(products,3)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        products_count = products.count()

    context = {
        'products':paged_products,
        'product_count':products_count,
    }
    return render(request,'store/store.html',context)


def product_detail(request,category_slug,product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug,slug=product_slug)

    except Exception as e:
        raise e

    reviews = ReviewRating.objects.filter(product_id =single_product.id,status=True)

    #get the product gallery
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)

    context = {
        'single_product':single_product,
        'reviews':reviews,
        'product_gallery':product_gallery
    }
    return render(request,'store/product_detail.html',context)


def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            products_count = products.count()
    context = {
        'products':products,
        'product_count':products_count,
    }
    return render(request,'store/store.html',context)

def submit_review(request,product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id,product__id=product_id)
            form = Reviewform(request.POST,instance=reviews)
            form.save()
            messages.success(request,"Thank you! your review has been updated..")
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = Reviewform(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request,"Thank you! your review has been submitted..")
                return redirect(url)

templates/store/booking_detail.html
{% extends 'base.html' %}
{% block content %}

<section class="section-content padding-y bg">
    {% include 'includes/alert.html' %}
    <div class="container">
        <div class="row">
            <main class="col-md-9">
                <article class="card">
                    <header class="card-header">
                        <strong class="d-inline-block mr-3">Edit your prfile</strong>
                    </header>
                    <div class="card-body">
                        <div class="text-right">
                            <img src="{{userprofile.profile_picture.url}}" alt="Profile Picture" width="100" style="border-radius:50px;">
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <form action="{% url 'edit_profile' %}" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="form-group col md-6">
                                            <label>First Name:</label>
                                            {{user_form.first_name}}
                                        </div>
                                        <div class="form-group col md-6">
                                            <label>Last Name:</label>
                                            {{user_form.last_name}}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col md-6">
                                            <label>Phone Number:</label>
                                            {{user_form.phone_number}}
                                        </div>
                                        <div class="form-group col md-6">
                                            <label>Profile Picture:</label>
                                            {{profile_form.profile_picture}}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Address Line 1:</label>
                                        {{profile_form.address_line_1}}
                                    </div>
                                    <div class="form-group">
                                        <label>Address Line 2:</label>
                                        {{profile_form.address_line_2}}
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col md-4">
                                            <label>City:</label>
                                            {{profile_form.city}}
                                        </div>
                                        <div class="form-group col md-4">
                                            <label>State:</label>
                                            {{profile_form.state}}
                                        </div>
                                        <div class="form-group col md-4">
                                            <label>Country:</label>
                                            {{profile_form.country}}
                                        </div>
                                    </div>
                                    <input type="submit" value="Save" class="form-control btn btn-primary">

                                </form>
                            </div>
                        </div>
                    </div>
                </article>
            </main>
        </div>
    </div>
</section>



{% endblock %}

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    
    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Quantity</th>
      <th scope="col" width="120">Price</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <figure class="itemside align-items-center">
                <div class="aside"><img src="{% static './images/items/11.jpg' %}" class="img-sm"></div>
                <figcaption class="info">
                    <a href="#" class="title text-dark">Camera Canon EOS M50 Kit</a>
                    <p class="text-muted small">Matrix: 25 Mpx <br> Brand: Canon</p>
                </figcaption>
            </figure>
        </td>
        <td> 
            <!-- col.// -->
                        <div class="col"> 
                            <div class="input-group input-spinner">
                                <div class="input-group-prepend">
                                <button class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </button>
                                </div>
                                <input type="text" class="form-control"  value="1">
                                <div class="input-group-append">
                                <button class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </button>
                                </div>
                            </div> <!-- input-group.// -->
                        </div> <!-- col.// -->
        </td>
        <td> 
            <div class="price-wrap"> 
                <var class="price">$1156.00</var> 
                <small class="text-muted"> $315.20 each </small> 
            </div> <!-- price-wrap .// -->
        </td>
        <td class="text-right"> 
        <a href="" class="btn btn-danger"> Remove</a>
        </td>
    </tr>
    </tbody>
    </table>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">$69.97</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> $10.00</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>$59.97</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static './images/misc/payments.png' %}" height="26">
                </p>
                <a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
                <a href="./store.html" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap mainImage">
           <center><img src="{{ single_product.images.url }}"></center>
        </div> <!-- img-big-wrap.// -->
        
    </article> <!-- gallery-wrap .end// -->
    <ul class="thumb">
        <li>
            <a href="{{ single_product.images.url }}" target="mainImage"><img src="{{ single_product.images.url }}" alt="Product Image"></a>
            {% for i in product_gallery %}
            <a href="{{i.image.url}}" target="mainImage"><img src="{{i.image.url}}" alt="Product Image"></a>
            {% endfor %}
        </li>
    </ul>
            </aside>
            <main class="col-md-6 border-left">
        <article class="content-body">
        
        <h2 class="title">{{ single_product.product_name }}</h2>
        <div class="rating-star">
            <span>
                <i class="fa fa-star{% if single_product.averagereview < 0.5 %}-o{% elif single_product.averagereview >= 0.5 and single_product.averagereview < 1  %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averagereview < 1.5 %}-o{% elif single_product.averagereview >= 1.5 and single_product.averagereview < 2  %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averagereview < 2.5 %}-o{% elif single_product.averagereview >= 2.5 and single_product.averagereview < 3  %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averagereview < 3.5 %}-o{% elif single_product.averagereview >= 3.5 and single_product.averagereview < 4  %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averagereview < 4.5 %}-o{% elif single_product.averagereview >= 4.5 and single_product.averagereview < 5  %}-half-o {% endif %}" aria-hidden="true"></i>
                <span>{{ single_product.countreview }} Reviews</span>
            </span>
        </div>

        
        <div class="mb-3"> 
            <var class="price h4">&#2547;{{ single_product.price }}</var> 
        </div> 
        
        <p>{{ single_product.description }}</p>
        
        
        <hr>
            <!-- <div class="row">
                <div class="item-option-select">
                    <h6>Choose Color</h6>
                    <select name="color" class="form-control" required>
                        <option value="" disabled selected>Select</option>
                        {% for i in single_product.variation_set.colors %}
                      <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                      {% endfor %}
                    </select>
                </div>
            </div> 
            <div class="row">
                <div class="item-option-select">
                    <h6>Select Size</h6>
                    <select name="size" class="form-control">
                        <option value="" disabled selected>Select</option>
                        {% for i in single_product.variation_set.sizes %}
                      <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                      {% endfor %}
                    </select>
                </div>
            </div> -->
            <hr>
            {% if single_product.stock <= 0 %}
            <h5 class="text-danger">No Room Available</h5>
            {% else %}
            <a href="{% url 'add' pk=single_product.pk %}" class="btn  btn-primary"> <span class="text">Book Now</span> <i class="fas fa-book"></i>  </a>
            {% endif %}
        </article> <!-- product-info-aside .// -->
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
                <div class="col-md-9">

        <form action="{% url 'submit_review'  single_product.id%}" method="POST">
            {% csrf_token %}
            <h5> Write Your Review</h5>
            <div>
                <!-- Rating stars -->
                <label>How do you rate this product</label>
                <br>
                <div class="rate">
                    <input type="radio" name="rating" id="rating10" value="5" required/><label for="rating10" title="5"></label>
                    <input type="radio" name="rating" id="rating9" value="4.5" required/><label for="rating9" title="4.5" class="half"></label>
                    <input type="radio" name="rating" id="rating8" value="4" required/><label for="rating8" title="4"></label>
                    <input type="radio" name="rating" id="rating7" value="3.5" required/><label for="rating7" title="3.5" class="half"></label>
                    <input type="radio" name="rating" id="rating6" value="3" required/><label for="rating6" title="3"></label>
                    <input type="radio" name="rating" id="rating5" value="2.5" required/><label for="rating5" title="2.5" class="half"></label>
                    <input type="radio" name="rating" id="rating4" value="2" required/><label for="rating4" title="2"></label>
                    <input type="radio" name="rating" id="rating3" value="1.5" required/><label for="rating3" title="1.5" class="half"></label>
                    <input type="radio" name="rating" id="rating2" value="1" required/><label for="rating2" title="1"></label>
                    <input type="radio" name="rating" id="rating1" value="0.5" required/><label for="rating1" title="0.5" class="half"></label>
                </div>
                <br>
                <header class="section-heading">
                    <h3>Customer Reviews </h3>
                    <div class="rating-star">
                        <span>
                            <i class="fa fa-star{% if single_product.averagereview < 0.5 %}-o{% elif single_product.averagereview >= 0.5 and single_product.averagereview < 1  %}-half-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_product.averagereview < 1.5 %}-o{% elif single_product.averagereview >= 1.5 and single_product.averagereview < 2  %}-half-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_product.averagereview < 2.5 %}-o{% elif single_product.averagereview >= 2.5 and single_product.averagereview < 3  %}-half-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_product.averagereview < 3.5 %}-o{% elif single_product.averagereview >= 3.5 and single_product.averagereview < 4  %}-half-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_product.averagereview < 4.5 %}-o{% elif single_product.averagereview >= 4.5 and single_product.averagereview < 5  %}-half-o {% endif %}" aria-hidden="true"></i>
                            <span>{{ single_product.countreview }} Reviews</span>
                        </span>
                    </div>
                    
                </header>

                Review Title:
                <input type="text" class="form-control" name="subject">
                <br>
                <textarea name="review" rows="4" class="form-control"></textarea>
                <br>
                {% if user.is_authenticated %}
                <input type="submit" value="Submit Review" class="btn btn-primary">
                {% else %}
                <p>Your must be logged in to post a review. <span><a href="{% url 'login' %}">Login now</a></span></p>
                {% endif %}
            </div>
            {% include 'includes/alert.html' %}
        </form>
        <br>

        {% for review in reviews %}
        <article class="box mb-3">
            <div class="icontext w-100">
                <img src="{% static './images/avatars/temp.webp'%}" class="img-xs icon rounded-circle">
                <div class="text">
                    <span class="date text-muted float-md-right">{{review.updated_at}} </span>  
                    <h6 class="mb-1">@{{review.user.username}} </h6>
                    <div class="rating-star">
                        <span>
                            <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                        </span>
                    </div>
                    
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <h6>{{review.subject}}</h6>
                <p>
                   {{review.review}}
                </p>	
            </div>
        </article>
        {% endfor %}
    
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}